import styles from './page.module.css';
import { Montserrat } from 'next/font/google';

const montse = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'GastroFest',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${styles.backgroundContainer}`}>{children}</body>
    </html>
  );
}
